#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_SKILLS_DIR="$PROJECT_ROOT/.agents/skills"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
step() { echo -e "${BLUE}==>${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

MODE="global"
FORCE="false"
TARGET=""

get_current_version() {
  local plugin_json="$PROJECT_ROOT/.claude-plugin/plugin.json"
  if [[ -f "$plugin_json" ]]; then
    grep -o '"version":\s*"[^"]*"' "$plugin_json" | cut -d'"' -f4
  else
    echo "unknown"
  fi
}

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Install Codex wrapper skills generated by Hyperpowers.

Options:
  --global              Install to ~/.agents/skills (default)
  --local               Install to <target>/.agents/skills
  --target <path>       Base path for --local mode (default: current directory)
  --force               Reinstall even if same version is already installed
  --status              Show install status
  --version             Show current and installed version
  -h, --help            Show this message

Examples:
  $(basename "$0") --global
  $(basename "$0") --local --target /path/to/project
  $(basename "$0") --global --force
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --global)
      MODE="global"
      shift
      ;;
    --local)
      MODE="local"
      shift
      ;;
    --target)
      TARGET="${2:-}"
      [[ -z "$TARGET" ]] && error "--target requires a value"
      shift 2
      ;;
    --force)
      FORCE="true"
      shift
      ;;
    --status)
      STATUS_ONLY="true"
      shift
      ;;
    --version)
      VERSION_ONLY="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      error "Unknown option: $1"
      ;;
  esac
done

if [[ ! -d "$SOURCE_SKILLS_DIR" ]]; then
  error "Source wrappers not found: $SOURCE_SKILLS_DIR. Run: node scripts/sync-codex-skills.js --write"
fi

SOURCE_COUNT=0
for dir in "$SOURCE_SKILLS_DIR"/codex-*; do
  if [[ -d "$dir" ]]; then
    SOURCE_COUNT=$((SOURCE_COUNT + 1))
  fi
done
[[ $SOURCE_COUNT -eq 0 ]] && error "No codex-* wrappers found in $SOURCE_SKILLS_DIR"

if [[ "$MODE" == "global" ]]; then
  AGENTS_ROOT="$HOME/.agents"
else
  BASE_TARGET="${TARGET:-$PWD}"
  AGENTS_ROOT="$BASE_TARGET/.agents"
fi

TARGET_SKILLS_DIR="$AGENTS_ROOT/skills"
VERSION_FILE="$AGENTS_ROOT/.hyperpowers-codex-version"
BACKUP_ROOT="$AGENTS_ROOT/.hyperpowers-codex-backup"

CURRENT_VERSION="$(get_current_version)"
INSTALLED_VERSION="none"
if [[ -f "$VERSION_FILE" ]]; then
  INSTALLED_VERSION="$(cat "$VERSION_FILE")"
fi

show_status() {
  echo "Codex Wrapper Install Status"
  echo "==========================="
  echo "Mode: $MODE"
  echo "Target root: $AGENTS_ROOT"
  echo "Current version: $CURRENT_VERSION"
  echo "Installed version: $INSTALLED_VERSION"

  local installed_count=0
  if [[ -d "$TARGET_SKILLS_DIR" ]]; then
    for dir in "$TARGET_SKILLS_DIR"/codex-*; do
      [[ -d "$dir" ]] && installed_count=$((installed_count + 1))
    done
  fi

  echo "Installed wrappers: $installed_count"
}

if [[ "${VERSION_ONLY:-false}" == "true" ]]; then
  echo "Current: $CURRENT_VERSION"
  echo "Installed: $INSTALLED_VERSION"
  exit 0
fi

if [[ "${STATUS_ONLY:-false}" == "true" ]]; then
  show_status
  exit 0
fi

backup_existing() {
  local has_existing="false"
  if [[ -d "$TARGET_SKILLS_DIR" ]]; then
    for dir in "$TARGET_SKILLS_DIR"/codex-*; do
      if [[ -d "$dir" ]]; then
        has_existing="true"
        break
      fi
    done
  fi

  if [[ "$has_existing" != "true" ]]; then
    return
  fi

  local stamp
  stamp="backup-$(date +%Y%m%d-%H%M%S)"
  local backup_dir="$BACKUP_ROOT/$stamp"

  step "Backing up existing codex wrappers..."
  mkdir -p "$backup_dir/skills"

  for dir in "$TARGET_SKILLS_DIR"/codex-*; do
    if [[ -d "$dir" ]]; then
      cp -R "$dir" "$backup_dir/skills/"
    fi
  done

  if [[ -f "$VERSION_FILE" ]]; then
    cp "$VERSION_FILE" "$backup_dir/version"
  fi

  info "Backup created: $backup_dir"
}

cleanup_backups() {
  if [[ ! -d "$BACKUP_ROOT" ]]; then
    return
  fi

  local backup_count
  backup_count="$(ls -1 "$BACKUP_ROOT" 2>/dev/null | wc -l | tr -d ' ')"
  if [[ "$backup_count" -le 3 ]]; then
    return
  fi

  ls -1t "$BACKUP_ROOT" | tail -n +4 | while read -r old_backup; do
    rm -rf "$BACKUP_ROOT/$old_backup"
  done
}

if [[ "$CURRENT_VERSION" == "$INSTALLED_VERSION" && "$FORCE" != "true" ]]; then
  info "Codex wrappers version $CURRENT_VERSION already installed at $TARGET_SKILLS_DIR"
  info "Use --force to reinstall"
  exit 0
fi

mkdir -p "$TARGET_SKILLS_DIR"
backup_existing

step "Installing codex wrappers..."
for dir in "$SOURCE_SKILLS_DIR"/codex-*; do
  if [[ -d "$dir" ]]; then
    name="$(basename "$dir")"
    rm -rf "$TARGET_SKILLS_DIR/$name"
    cp -R "$dir" "$TARGET_SKILLS_DIR/$name"
  fi
done

echo "$CURRENT_VERSION" > "$VERSION_FILE"
cleanup_backups

echo
info "Codex wrappers installed successfully"
info "Mode: $MODE"
info "Target: $TARGET_SKILLS_DIR"
info "Version: $CURRENT_VERSION"
